import { DefaultTheme } from 'react-native-paper';

export const paperTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    primary: '#349eeb',
    secondary: '#03b6fc',
    error: '#f13a59',
    underlineColor: 'transparent',
    text:'white',
    headerColor:'#039dfc',
    mainColor:'#3271a8'
  },
};
export const mainTheme = {
    headerColor:'#1c2127',
    headerTextColor:"white",
    tabBarUnderlineStyle:"white",
    tabHeading:"white",
    drawerIconColor:"white",
    mainColor:'#1E252B',
    backgroundColor:"#1E252B",
    recordTabCardBackground:"#3246a8",
    recordTabcardItemLabelColor:"white",
    recordTabcardItemTextColor:"#dff9fb",
    recordTabCircle1Color:"#0044ff",
    recordTabCircle2Color:"#0044ff",
    recordTabCircle3Color:"#0044ff",
    recordTabCircle1TextColor:"white",
    recordTabCircle2TextColor:"white",
    recordTabCircle3TextColor:"white",
    sideBarTextColor:"white",
    activeSideBarItemColor:"#032cfc",
    sideBarLogoTextColor:"white",
    buyColor:"#4cd137",
    sellColor:"#b81c1c",
    liveSignalItemColor:"white",
    liveSignalHeaderTextColor:"#ec9a14",
    liveSignalBorderColor:"blue",
    closedSignalItemColor:"white",
    closedSignalHeaderTextColor:"#ec9a14",
    closedSignalBorderColor:"blue",
    demoSignalItemColor:"white",
    demoSignalHeaderTextColor:"#ec9a14",
    demoSignalBorderColor:"blue",
    stopLossColor:"#e74c3c",
    takeProfitColor:"#1AACEB",
    demoLabelColor:"white",
    demoScreenHeaderColor:'yellow',
    demoGmtLabelColor:"#bdc3c7",
    settingsScreenLanguageColor:"white",
    contactScreenTextColor:'white',
    contactScreenButtonColor:'#3498db',
    trialPeriodIconColor:'white',
    trialPeriodTextColor:'white',
    onBoardingScreen1Color:'#00a2e3',
    onBoardingScreen2Color:'#0676bd',
    onBoardingScreen3Color:'#42b0f5',
    fxBlueExplanationColor:'#327ba8',
    demoGmtLabelStyle:'white'
};
export const blueTheme = {
  mainColor:'#3271a8',
  backgroundColor:"#349eeb",
};
export const darkTheme = {
  mainColor:'#3271a8',
  backgroundColor:"#349eeb",
};